-- Limitless Store: Complete 120-Product Database Restoration
-- Optimized for TEXT IDs and Array Fields (Sizes, Colors, Gallery)

TRUNCATE TABLE products CASCADE;

INSERT INTO products (
  id, name, slug, description, price, category, subcategory, 
  image_url, images, gallery_images, sizes, colors, 
  rating, reviews, character_slug, is_featured, stock
) VALUES
-- ──────── GOJO SATORU ────────
('gojo-tshirt-01', 'Gojo Satoru Tech T-Shirt', 'gojo-tshirt-01', 'Gojo Satoru Technique T-Shirt — Infinity Series.', 2500, 'clothing', 't-shirt', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg', '/images/gojo-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'White'], 4.8, 124, 'gojo', true, 20),
('gojo-hoodie-01', 'Limitless Signature Hoodie', 'gojo-hoodie-01', 'Limitless Signature Hoodie — Ultimate Comfort Artifact.', 4800, 'clothing', 'hoodie', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Navy'], 4.9, 256, 'gojo', false, 20),
('gojo-pants-01', 'Tokyo High Training Pants', 'gojo-pants-01', 'Tokyo High Training Pants — Six Eyes Perception Fit.', 3200, 'clothing', 'pants', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 64, 'gojo', false, 20),
('gojo-manga-01', 'JJK Vol. 1 — Gojo Cover', 'gojo-manga-01', 'JJK Vol. 1 — Gojo Cover Edition.', 1200, 'manga', 'volume', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 5.0, 512, 'gojo', true, 20),
('gojo-artbook-01', 'Infinity Art Book', 'gojo-artbook-01', 'Infinity Art Book — Gojo Satoru Collection.', 2800, 'manga', 'artbook', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.9, 89, 'gojo', false, 20),
('gojo-poster-01', 'Domain Expansion Poster', 'gojo-poster-01', 'Domain Expansion — Unlimited Void Art Print.', 1800, 'wallart', 'poster', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.7, 42, 'gojo', false, 20),
('gojo-canvas-01', 'Six Eyes Canvas 50×70cm', 'gojo-canvas-01', 'Six Eyes Canvas 50×70cm — High-End Artifact.', 3500, 'wallart', 'canvas', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.8, 31, 'gojo', false, 20),
('gojo-figure-01', 'Gojo Satoru 25cm PVC', 'gojo-figure-01', 'Gojo Satoru 25cm PVC — Hollow Purple Pose.', 6500, 'figurines', 'pvc', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.9, 144, 'gojo', true, 20),
('gojo-nendo-01', 'Gojo Satoru Nendoroid', 'gojo-nendo-01', 'Gojo Satoru Nendoroid — Masked Version.', 8900, 'figurines', 'nendoroid', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 5.0, 201, 'gojo', false, 20),
('gojo-keychain-01', 'Six Eyes Keychain', 'gojo-keychain-01', 'Six Eyes Keychain — Cursed Tool Grade.', 800, 'accessories', 'keychain', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.4, 88, 'gojo', false, 20),

-- ──────── RYOMEN SUKUNA ────────
('sukuna-tshirt-01', 'King of Curses Tee', 'sukuna-tshirt-01', 'King of Curses Tee — Malevolent Shrine Series.', 2500, 'clothing', 't-shirt', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Dark Red'], 4.8, 412, 'sukuna', true, 20),
('sukuna-hoodie-01', 'Cleave & Dismantle Hoodie', 'sukuna-hoodie-01', 'Cleave & Dismantle Hoodie — Dark Essence Fabric.', 4800, 'clothing', 'hoodie', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Vile Purple'], 4.9, 192, 'sukuna', false, 20),
('sukuna-pants-01', 'Heian Era Joggers', 'sukuna-pants-01', 'Heian Era Joggers — High-Performance Artifact.', 3200, 'clothing', 'pants', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], ARRAY['S', 'M', 'L'], ARRAY['Black'], 4.5, 87, 'sukuna', false, 20),
('sukuna-manga-01', 'JJK Vol. 1 — Sukuna Cover', 'sukuna-manga-01', 'JJK Vol. 1 — Sukuna Cover Edition.', 1200, 'manga', 'volume', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 5.0, 612, 'sukuna', true, 20),
('sukuna-artbook-01', 'Malevolent Art Collection', 'sukuna-artbook-01', 'Malevolent Art Collection — Sukuna Chronicle.', 2800, 'manga', 'artbook', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.9, 102, 'sukuna', false, 20),
('sukuna-poster-01', 'Shrine Domain Poster', 'sukuna-poster-01', 'Shrine Domain Expansion — Malevolent Shrine Art.', 1800, 'wallart', 'poster', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.7, 56, 'sukuna', false, 20),
('sukuna-canvas-01', 'King of Curses Canvas', 'sukuna-canvas-01', 'King of Curses Canvas — 50x70cm Premium.', 3500, 'wallart', 'canvas', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.8, 44, 'sukuna', false, 20),
('sukuna-figure-01', 'Sukuna 25cm PVC Statue', 'sukuna-figure-01', 'Sukuna 25cm PVC Statue — Throne Pose.', 6500, 'figurines', 'pvc', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.9, 182, 'sukuna', true, 20),
('sukuna-nendo-01', 'Sukuna Nendoroid', 'sukuna-nendo-01', 'Sukuna Nendoroid — Cursed Finger Included.', 8900, 'figurines', 'nendoroid', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 5.0, 245, 'sukuna', false, 0),
('sukuna-keychain-01', 'Cursed Finger Keychain', 'sukuna-keychain-01', 'Cursed Finger Keychain — Grade Special Tool.', 800, 'accessories', 'keychain', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.2, 115, 'sukuna', false, 20),

-- ──────── YUJI ITADORI ────────
('yuji-tshirt-01', 'Divergent Fist Tee', 'yuji-tshirt-01', 'Divergent Fist Tee — Itadori Series.', 2500, 'clothing', 't-shirt', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Pink'], 4.6, 92, 'yuji', true, 20),
('yuji-hoodie-01', 'Tiger of West Junior Hoodie', 'yuji-hoodie-01', 'Tiger of West Junior Hoodie — Heavyweight Artifact.', 4800, 'clothing', 'hoodie', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Dark Pink'], 4.8, 156, 'yuji', false, 20),
('yuji-pants-01', 'Combat Ready Joggers', 'yuji-pants-01', 'Combat Ready Joggers — High-Dexterity Fabric.', 3200, 'clothing', 'pants', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], ARRAY['S', 'M', 'L'], ARRAY['Black'], 4.4, 52, 'yuji', false, 20),
('yuji-manga-01', 'JJK Vol. 1 — Yuji Cover', 'yuji-manga-01', 'JJK Vol. 1 — Yuji Cover Edition.', 1200, 'manga', 'volume', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.9, 412, 'yuji', true, 20),
('yuji-artbook-01', 'Unbreakable Art Book', 'yuji-artbook-01', 'Unbreakable Art Book — Itadori Yuji Collection.', 2800, 'manga', 'artbook', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.7, 76, 'yuji', false, 20),
('yuji-poster-01', 'Black Flash Art Print', 'yuji-poster-01', 'Black Flash Art Print — Cursed Energy Spark.', 1800, 'wallart', 'poster', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.5, 61, 'yuji', false, 20),
('yuji-canvas-01', 'Divergent Fist Canvas', 'yuji-canvas-01', 'Divergent Fist Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.6, 38, 'yuji', false, 20),
('yuji-figure-01', 'Yuji Itadori 25cm Figure', 'yuji-figure-01', 'Yuji Itadori 25cm Figure — Combat Stance.', 6500, 'figurines', 'pvc', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.8, 124, 'yuji', true, 20),
('yuji-nendo-01', 'Yuji Itadori Nendoroid', 'yuji-nendo-01', 'Yuji Itadori Nendoroid — Radiant Smile Edition.', 8900, 'figurines', 'nendoroid', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 5.0, 192, 'yuji', false, 20),
('yuji-keychain-01', 'JJK Emblem Keychain', 'yuji-keychain-01', 'JJK Emblem Keychain — Yuji Version.', 800, 'accessories', 'keychain', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.3, 108, 'yuji', false, 20),

-- ──────── MEGUMI FUSHIGURO ────────
('megumi-tshirt-01', 'Ten Shadows Tee', 'megumi-tshirt-01', 'Ten Shadows Tee — Divine Dogs Series.', 2500, 'clothing', 't-shirt', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Dark Blue'], 4.7, 84, 'megumi', true, 20),
('megumi-hoodie-01', 'Shadow Ripple Hoodie', 'megumi-hoodie-01', 'Shadow Ripple Hoodie — Fushiguro Clan Artifact.', 4800, 'clothing', 'hoodie', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Navy', 'Black'], 4.9, 112, 'megumi', false, 20),
('megumi-pants-01', 'Sorcerer Patrol Pants', 'megumi-pants-01', 'Sorcerer Patrol Pants — Durable Mesh Fabric.', 3200, 'clothing', 'pants', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 42, 'megumi', false, 20),
('megumi-manga-01', 'JJK Vol. 1 — Megumi Edition', 'megumi-manga-01', 'JJK Vol. 1 — Megumi Cover Edition.', 1200, 'manga', 'volume', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 5.0, 312, 'megumi', true, 20),
('megumi-artbook-01', 'Shadow Art Collection', 'megumi-artbook-01', 'Shadow Art Collection — Ten Shadows Guide.', 2800, 'manga', 'artbook', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.8, 56, 'megumi', false, 20),
('megumi-poster-01', 'Chimera Shadow Poster', 'megumi-poster-01', 'Domain Expansion — Chimera Shadow Garden Art Print.', 1800, 'wallart', 'poster', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.6, 38, 'megumi', false, 20),
('megumi-canvas-01', 'Divine Dogs Canvas', 'megumi-canvas-01', 'Divine Dogs Canvas — Shadow Totem Series.', 3500, 'wallart', 'canvas', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.7, 24, 'megumi', false, 20),
('megumi-figure-01', 'Megumi 25cm PVC Statue', 'megumi-figure-01', 'Megumi 25cm PVC Statue — Divine Dogs Included.', 6500, 'figurines', 'pvc', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.9, 98, 'megumi', true, 20),
('megumi-nendo-01', 'Megumi Fushiguro Nendoroid', 'megumi-nendo-01', 'Megumi Fushiguro Nendoroid — Summoning Hands Edition.', 8900, 'figurines', 'nendoroid', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 5.0, 142, 'megumi', false, 20),
('megumi-keychain-01', 'Ten Shadows Keychain', 'megumi-keychain-01', 'Ten Shadows Keychain — Shadow Totem Gem.', 800, 'accessories', 'keychain', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.4, 76, 'megumi', false, 20),

-- ──────── TOJI FUSHIGURO ────────
('toji-tshirt-01', 'Sorcerer Killer Tee', 'toji-tshirt-01', 'Sorcerer Killer Tee — Heavenly Restriction Series.', 2500, 'clothing', 't-shirt', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black', 'Dark Gray'], 4.8, 156, 'toji', true, 20),
('toji-hoodie-01', 'Worm-Spirit Cape Hoodie', 'toji-hoodie-01', 'Worm-Spirit Cape Hoodie — Peak Physique Fit.', 4800, 'clothing', 'hoodie', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], ARRAY['L', 'XL', 'XXL'], ARRAY['Black'], 4.9, 87, 'toji', false, 20),
('toji-pants-01', 'Inverted Spear Joggers', 'toji-pants-01', 'Inverted Spear Joggers — Tactical Mesh Fabric.', 3200, 'clothing', 'pants', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.6, 52, 'toji', false, 20),
('toji-manga-01', 'JJK Vol. 1 — Toji Edition', 'toji-manga-01', 'JJK Vol. 1 — Toji Edition - Legacy Collection.', 1200, 'manga', 'volume', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 5.0, 214, 'toji', true, 20),
('toji-artbook-01', 'Legacy of Heaven Book', 'toji-artbook-01', 'Legacy of Heaven Art Book — Hidden Inventory Chapter.', 2800, 'manga', 'artbook', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 4.9, 76, 'toji', false, 20),
('toji-poster-01', 'Inverted Spear Art Print', 'toji-poster-01', 'Inverted Spear Art Print — Sorcerer Killer Visual.', 1800, 'wallart', 'poster', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 4.7, 42, 'toji', false, 20),
('toji-canvas-01', 'Heavenly Restriction Canvas', 'toji-canvas-01', 'Heavenly Restriction Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 4.8, 31, 'toji', false, 20),
('toji-figure-01', 'Toji 25cm PVC Statue', 'toji-figure-01', 'Toji 25cm PVC Statue — Worm Spirit Accessory.', 6500, 'figurines', 'pvc', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 4.9, 119, 'toji', true, 20),
('toji-nendo-01', 'Toji Fushiguro Nendoroid', 'toji-nendo-01', 'Toji Fushiguro Nendoroid — Sorcerer Killer Edition.', 8900, 'figurines', 'nendoroid', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 5.0, 192, 'toji', false, 0),
('toji-keychain-01', 'Playful Cloud Keychain', 'toji-keychain-01', 'Playful Cloud Keychain — Special Grade Tool.', 800, 'accessories', 'keychain', '/images/toji-card.jpg', ARRAY['/images/toji-card.jpg'], ARRAY['/images/toji-card.jpg'], '{}', '{}', 4.4, 68, 'toji', false, 20),

-- ──────── YUTA OKKOTSU ────────
('yuta-tshirt-01', 'Rika Manifest Tee', 'yuta-tshirt-01', 'Rika Manifest Tee — Special Grade Collection.', 2500, 'clothing', 't-shirt', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['White', 'Silver'], 4.8, 142, 'yuta', true, 20),
('yuta-hoodie-01', 'Copy Technique Hoodie', 'yuta-hoodie-01', 'Copy Technique Hoodie — Pure Love Fabric.', 4800, 'clothing', 'hoodie', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Gray', 'Navy'], 4.9, 156, 'yuta', false, 20),
('yuta-pants-01', 'Rika Protection Joggers', 'yuta-pants-01', 'Rika Protection Joggers — High-Energy Shielding.', 3200, 'clothing', 'pants', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Navy'], 4.5, 42, 'yuta', false, 20),
('yuta-manga-01', 'JJK Vol. 0 — Yuta Edition', 'yuta-manga-01', 'JJK Vol. 0 — Yuta Cover Edition.', 1200, 'manga', 'volume', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 5.0, 512, 'yuta', true, 20),
('yuta-artbook-01', 'Pure Love Art Book', 'yuta-artbook-01', 'Pure Love Art Book — Yuta Okkotsu Chronicle.', 2800, 'manga', 'artbook', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 4.9, 87, 'yuta', false, 20),
('yuta-poster-01', 'Rika Domain Poster', 'yuta-poster-01', 'Rika Queen of Curses — Domain Expansion Art Print.', 1800, 'wallart', 'poster', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 4.7, 52, 'yuta', false, 20),
('yuta-canvas-01', 'Special Grade Canvas', 'yuta-canvas-01', 'Special Grade Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 4.8, 38, 'yuta', false, 20),
('yuta-figure-01', 'Yuta 25cm PVC Statue', 'yuta-figure-01', 'Yuta 25cm PVC Statue — Rika Eye Accents.', 6500, 'figurines', 'pvc', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 4.9, 134, 'yuta', true, 20),
('yuta-nendo-01', 'Yuta Okkotsu Nendoroid', 'yuta-nendo-01', 'Yuta Okkotsu Nendoroid — Pure Love Edition.', 8900, 'figurines', 'nendoroid', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 5.0, 198, 'yuta', false, 20),
('yuta-keychain-01', 'Engagement Ring Keychain', 'yuta-keychain-01', 'Engagement Ring Keychain — Rika Orimoto Ver.', 800, 'accessories', 'keychain', '/images/yuta-card.jpg', ARRAY['/images/yuta-card.jpg'], ARRAY['/images/yuta-card.jpg'], '{}', '{}', 4.5, 92, 'yuta', false, 20),

-- ──────── MAKI ZENIN ────────
('maki-tshirt-01', 'Zenin Rebel Tee', 'maki-tshirt-01', 'Zenin Rebel Tee — Cursed Tool Master Series.', 2500, 'clothing', 't-shirt', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Green'], 4.8, 112, 'maki', true, 20),
('maki-hoodie-01', 'Heavenly Restriction Hoodie', 'maki-hoodie-01', 'Heavenly Restriction Hoodie — Zero Cursed Energy Fit.', 4800, 'clothing', 'hoodie', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Dark Green', 'Black'], 4.9, 145, 'maki', false, 20),
('maki-pants-01', 'Zenin Training Pants', 'maki-pants-01', 'Zenin Training Pants — High-Impact Mobility.', 3200, 'clothing', 'pants', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Olive'], 4.5, 48, 'maki', false, 20),
('maki-manga-01', 'JJK Vol. 1 — Maki Edition', 'maki-manga-01', 'JJK Vol. 1 — Maki Cover Edition.', 1200, 'manga', 'volume', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 5.0, 212, 'maki', true, 20),
('maki-artbook-01', 'Zenin Legacy Book', 'maki-artbook-01', 'Zenin Legacy Art Book — Maki Zenin Chapter.', 2800, 'manga', 'artbook', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 4.9, 67, 'maki', false, 20),
('maki-poster-01', 'Dragon Bone Poster', 'maki-poster-01', 'Dragon Bone Cursed Tool — Maki Zenin Art Print.', 1800, 'wallart', 'poster', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 4.7, 34, 'maki', false, 20),
('maki-canvas-01', 'Supernatural Senses Canvas', 'maki-canvas-01', 'Supernatural Senses Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 4.8, 28, 'maki', false, 20),
('maki-figure-01', 'Maki 25cm PVC Statue', 'maki-figure-01', 'Maki 25cm PVC Statue — Cursed Tool Arsenal.', 6500, 'figurines', 'pvc', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 4.9, 114, 'maki', true, 20),
('maki-nendo-01', 'Maki Zenin Nendoroid', 'maki-nendo-01', 'Maki Zenin Nendoroid — Combat Glasses Ver.', 8900, 'figurines', 'nendoroid', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 5.0, 168, 'maki', false, 20),
('maki-keychain-01', 'Dragon Bone Keychain', 'maki-keychain-01', 'Dragon Bone Keychain — Special Grade Tool.', 800, 'accessories', 'keychain', '/images/maki-card.jpg', ARRAY['/images/maki-card.jpg'], ARRAY['/images/maki-card.jpg'], '{}', '{}', 4.4, 72, 'maki', false, 20),

-- ──────── SUGURU GETO ────────
('geto-tshirt-01', 'Monkey Hater Tee', 'geto-tshirt-01', 'Monkey Hater Tee — Cursed Spirit Manipulation Series.', 2500, 'clothing', 't-shirt', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Gold'], 4.8, 124, 'geto', true, 20),
('geto-hoodie-01', 'Uzumaki Essence Hoodie', 'geto-hoodie-01', 'Uzumaki Essence Hoodie — Special Grade Curse Fabric.', 4800, 'clothing', 'hoodie', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Purple', 'Black'], 4.9, 142, 'geto', false, 20),
('geto-pants-01', 'Curse User Joggers', 'geto-pants-01', 'Curse User Joggers — High-Energy Absorption.', 3200, 'clothing', 'pants', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 52, 'geto', false, 20),
('geto-manga-01', 'JJK Vol. 1 — Suguru Edition', 'geto-manga-01', 'JJK Vol. 1 — Suguru Edition - Legacy Collection.', 1200, 'manga', 'volume', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 5.0, 245, 'geto', true, 20),
('geto-artbook-01', 'Curse Manipulation Guide', 'geto-artbook-01', 'Curse Manipulation Art Book — Geto Suguru Legacy.', 2800, 'manga', 'artbook', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 4.9, 92, 'geto', false, 20),
('geto-poster-01', 'Uzumaki Technique Poster', 'geto-poster-01', 'Maximum: Uzumaki — Suguru Geto Art Print.', 1800, 'wallart', 'poster', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 4.7, 48, 'geto', false, 20),
('geto-canvas-01', 'Cursed Womb Canvas', 'geto-canvas-01', 'Cursed Womb Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 4.8, 36, 'geto', false, 20),
('geto-figure-01', 'Geto 25cm PVC Statue', 'geto-figure-01', 'Geto 25cm PVC Statue — Curse Orb Accessory.', 6500, 'figurines', 'pvc', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 4.9, 112, 'geto', true, 20),
('geto-nendo-01', 'Suguru Geto Nendoroid', 'geto-nendo-01', 'Suguru Geto Nendoroid — Monk Attire Ver.', 8900, 'figurines', 'nendoroid', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 5.0, 156, 'geto', false, 20),
('geto-keychain-01', 'Curse Orb Keychain', 'geto-keychain-01', 'Curse Orb Keychain — Sorcerer Grade Tool.', 800, 'accessories', 'keychain', '/images/geto-card.jpg', ARRAY['/images/geto-card.jpg'], ARRAY['/images/geto-card.jpg'], '{}', '{}', 4.4, 74, 'geto', false, 20),

-- ──────── CHOSO ────────
('choso-tshirt-01', 'Piercing Blood Tee', 'choso-tshirt-01', 'Piercing Blood Tee — Death Painting Series.', 2500, 'clothing', 't-shirt', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Blood Red'], 4.8, 92, 'choso', true, 20),
('choso-hoodie-01', 'Supernova Pulse Hoodie', 'choso-hoodie-01', 'Supernova Pulse Hoodie — Hybrid Existence Fabric.', 4800, 'clothing', 'hoodie', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Maroon', 'Black'], 4.9, 115, 'choso', false, 20),
('choso-pants-01', 'Blood Manipulation Joggers', 'choso-pants-01', 'Blood Manipulation Joggers — High-Cohesion Artifact.', 3200, 'clothing', 'pants', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 38, 'choso', false, 20),
('choso-manga-01', 'JJK Vol. 1 — Choso Edition', 'choso-manga-01', 'JJK Vol. 1 — Choso Cover Edition.', 1200, 'manga', 'volume', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 5.0, 185, 'choso', true, 20),
('choso-artbook-01', 'Womb Art Collection', 'choso-artbook-01', 'Womb Art Collection — Death Painting Chronicle.', 2800, 'manga', 'artbook', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 4.9, 64, 'choso', false, 20),
('choso-poster-01', 'Flowing Red Art Print', 'choso-poster-01', 'Flowing Red Scale — Choso Art Print.', 1800, 'wallart', 'poster', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 4.7, 31, 'choso', false, 20),
('choso-canvas-01', 'Eldest Brother Canvas', 'choso-canvas-01', 'Eldest Brother Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 4.8, 24, 'choso', false, 20),
('choso-figure-01', 'Choso 25cm PVC Statue', 'choso-figure-01', 'Choso 25cm PVC Statue — Blood Splicing Pose.', 6500, 'figurines', 'pvc', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 4.9, 92, 'choso', true, 20),
('choso-nendo-01', 'Choso Nendoroid', 'choso-nendo-01', 'Choso Nendoroid — Brotherly Love Edition.', 8900, 'figurines', 'nendoroid', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 5.0, 126, 'choso', false, 20),
('choso-keychain-01', 'Blood Spike Keychain', 'choso-keychain-01', 'Blood Spike Keychain — Death Painting Tool.', 800, 'accessories', 'keychain', '/images/choso-card.jpg', ARRAY['/images/choso-card.jpg'], ARRAY['/images/choso-card.jpg'], '{}', '{}', 4.4, 62, 'choso', false, 20),

-- ──────── NANAMI KENTO ────────
('nanami-tshirt-01', '7:3 Ratio Tee', 'nanami-tshirt-01', '7:3 Ratio Tee — Corporate Sorcerer Series.', 2500, 'clothing', 't-shirt', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['White', 'Tan'], 4.8, 115, 'nanami', true, 20),
('nanami-hoodie-01', 'Overtime Essence Hoodie', 'nanami-hoodie-01', 'Overtime Essence Hoodie — High-Efficiency Fabric.', 4800, 'clothing', 'hoodie', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Khaki', 'Black'], 4.9, 134, 'nanami', false, 20),
('nanami-pants-01', 'Salaryman Combat Slacks', 'nanami-pants-01', 'Salaryman Combat Slacks — Breathable Professional.', 3200, 'clothing', 'pants', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Tan'], 4.5, 46, 'nanami', false, 20),
('nanami-manga-01', 'JJK Vol. 1 — Nanami Edition', 'nanami-manga-01', 'JJK Vol. 1 — Nanami Cover Edition.', 1200, 'manga', 'volume', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 5.0, 215, 'nanami', true, 20),
('nanami-artbook-01', 'Modern Sorcery Book', 'nanami-artbook-01', 'Modern Sorcery Art Book — Nanami Kento Legacy.', 2800, 'manga', 'artbook', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 4.9, 78, 'nanami', false, 20),
('nanami-poster-01', '7:3 Mark Poster', 'nanami-poster-01', 'Ratio Technique — Weak Point Art Print.', 1800, 'wallart', 'poster', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 4.7, 34, 'nanami', false, 20),
('nanami-canvas-01', 'Overtime Protocol Canvas', 'nanami-canvas-01', 'Overtime Protocol Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 4.8, 28, 'nanami', false, 20),
('nanami-figure-01', 'Nanami 25cm PVC Statue', 'nanami-figure-01', 'Nanami 25cm PVC Statue — Cleaver Accessory.', 6500, 'figurines', 'pvc', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 4.9, 126, 'nanami', true, 20),
('nanami-nendo-01', 'Nanami Kento Nendoroid', 'nanami-nendo-01', 'Nanami Kento Nendoroid — Relaxed Ver.', 8900, 'figurines', 'nendoroid', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 5.0, 168, 'nanami', false, 20),
('nanami-keychain-01', 'Blunt Cleaver Keychain', 'nanami-keychain-01', 'Blunt Cleaver Keychain — Sorcerer Grade Tool.', 800, 'accessories', 'keychain', '/images/nanami-card.jpg', ARRAY['/images/nanami-card.jpg'], ARRAY['/images/nanami-card.jpg'], '{}', '{}', 4.4, 76, 'nanami', false, 20),

-- ──────── KENJAKU ────────
('kenjaku-tshirt-01', 'Ancient Brain Tee', 'kenjaku-tshirt-01', 'Ancient Brain Tee — Millennial Weaver Series.', 2500, 'clothing', 't-shirt', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Dark Teal'], 4.8, 87, 'kenjaku', true, 20),
('kenjaku-hoodie-01', 'Evolution Protocol Hoodie', 'kenjaku-hoodie-01', 'Evolution Protocol Hoodie — Dark Matter Fabric.', 4800, 'clothing', 'hoodie', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Teal', 'Black'], 4.9, 102, 'kenjaku', false, 20),
('kenjaku-pants-01', 'Brain Transplant Joggers', 'kenjaku-pants-01', 'Brain Transplant Joggers — High-Energy Channeling.', 3200, 'clothing', 'pants', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 34, 'kenjaku', false, 20),
('kenjaku-manga-01', 'JJK Vol. 1 — Kenjaku Edition', 'kenjaku-manga-01', 'JJK Vol. 1 — Kenjaku Cover Edition.', 1200, 'manga', 'volume', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 5.0, 156, 'kenjaku', true, 20),
('kenjaku-artbook-01', 'Evolutionary Art Book', 'kenjaku-artbook-01', 'Evolutionary Art Book — Kenjaku Legacy.', 2800, 'manga', 'artbook', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 4.9, 56, 'kenjaku', false, 20),
('kenjaku-poster-01', 'Prison Realm Art Print', 'kenjaku-poster-01', 'Prison Realm — Gate of Sealing Art Print.', 1800, 'wallart', 'poster', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 4.7, 28, 'kenjaku', false, 20),
('kenjaku-canvas-01', 'Architect of Fate Canvas', 'kenjaku-canvas-01', 'Architect of Fate Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 4.8, 22, 'kenjaku', false, 20),
('kenjaku-figure-01', 'Kenjaku 25cm PVC Statue', 'kenjaku-figure-01', 'Kenjaku 25cm PVC Statue — Brain Reveal Ver.', 6500, 'figurines', 'pvc', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 4.9, 92, 'kenjaku', true, 0),
('kenjaku-nendo-01', 'Kenjaku Nendoroid', 'kenjaku-nendo-01', 'Kenjaku Nendoroid — Geto Body Ver.', 8900, 'figurines', 'nendoroid', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 5.0, 115, 'kenjaku', false, 20),
('kenjaku-keychain-01', 'Prison Realm Keychain', 'kenjaku-keychain-01', 'Prison Realm Keychain — Special Grade Tool.', 800, 'accessories', 'keychain', '/images/kenjaku-card.jpg', ARRAY['/images/kenjaku-card.jpg'], ARRAY['/images/kenjaku-card.jpg'], '{}', '{}', 4.4, 48, 'kenjaku', false, 20),

-- ──────── NOBARA KUGISAKI ────────
('nobara-tshirt-01', 'Hammer & Nails Tee', 'nobara-tshirt-01', 'Hammer & Nails Tee — Straw Doll Series.', 2500, 'clothing', 't-shirt', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Pink', 'Black'], 4.8, 142, 'nobara', true, 20),
('nobara-hoodie-01', 'Resonance Pulse Hoodie', 'nobara-hoodie-01', 'Resonance Pulse Hoodie — High-Fashion Artifact.', 4800, 'clothing', 'hoodie', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Fuchsia', 'Black'], 4.9, 115, 'nobara', false, 20),
('nobara-pants-01', 'Tokyo Fashion Slacks', 'nobara-pants-01', 'Tokyo Fashion Slacks — High-Mobility Canvas.', 3200, 'clothing', 'pants', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 48, 'nobara', false, 20),
('nobara-manga-01', 'JJK Vol. 1 — Nobara Edition', 'nobara-manga-01', 'JJK Vol. 1 — Nobara Cover Edition.', 1200, 'manga', 'volume', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 5.0, 212, 'nobara', true, 20),
('nobara-artbook-01', 'Vibrant Soul Art Book', 'nobara-artbook-01', 'Vibrant Soul Art Book — Nobara Kugisaki Collection.', 2800, 'manga', 'artbook', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 4.9, 74, 'nobara', false, 20),
('nobara-poster-01', 'Straw Doll Art Print', 'nobara-poster-01', 'Straw Doll Technique — Resonance Art Print.', 1800, 'wallart', 'poster', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 4.7, 42, 'nobara', false, 20),
('nobara-canvas-01', 'Nails of Fate Canvas', 'nobara-canvas-01', 'Nails of Fate Canvas — 50x70cm Framed.', 3500, 'wallart', 'canvas', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 4.8, 31, 'nobara', false, 20),
('nobara-figure-01', 'Nobara 25cm PVC Statue', 'nobara-figure-01', 'Nobara 25cm PVC Statue — Hammer Pose.', 6500, 'figurines', 'pvc', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 4.9, 114, 'nobara', true, 20),
('nobara-nendo-01', 'Nobara Kugisaki Nendoroid', 'nobara-nendo-01', 'Nobara Kugisaki Nendoroid — City Girl Edition.', 8900, 'figurines', 'nendoroid', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 5.0, 168, 'nobara', false, 20),
('nobara-keychain-01', 'Straw Doll Keychain', 'nobara-keychain-01', 'Straw Doll Keychain — Sorcerer Grade Tool.', 800, 'accessories', 'keychain', '/images/nobara-card.jpg', ARRAY['/images/nobara-card.jpg'], ARRAY['/images/nobara-card.jpg'], '{}', '{}', 4.4, 88, 'nobara', false, 20);
