-- Limitless Store: First 40 Products Seed (v2 Schema)
-- Includes gallery_images, sizes, and colors arrays

TRUNCATE TABLE products CASCADE;

INSERT INTO products (
  id, name, slug, description, price, category, subcategory, 
  image_url, images, gallery_images, sizes, colors, 
  rating, reviews, character_slug, is_featured, stock
) VALUES
-- GOJO SATORU (01-10)
('gojo-tshirt-01', 'Gojo Satoru Technique T-Shirt', 'gojo-tshirt-01', 'Gojo Satoru Technique T-Shirt - High-quality official merchandise inspired by Gojo Satoru. Featured Artifact.', 2500, 'clothing', 't-shirt', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg', '/images/gojo-card.jpg'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'White'], 4.8, 124, 'gojo', true, 20),
('gojo-hoodie-01', 'Gojo Satoru Signature Hoodie', 'gojo-hoodie-01', 'Gojo Satoru Signature Hoodie - High-quality official merchandise inspired by Gojo Satoru.', 4800, 'clothing', 'hoodie', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Navy'], 4.9, 256, 'gojo', false, 20),
('gojo-pants-01', 'Gojo Satoru Training Pants', 'gojo-pants-01', 'Gojo Satoru Training Pants - High-quality official merchandise inspired by Gojo Satoru.', 3200, 'clothing', 'pants', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 64, 'gojo', false, 20),
('gojo-manga-01', 'JJK Vol. 1 — Gojo Edition', 'gojo-manga-01', 'JJK Vol. 1 — Gojo Edition - High-quality official merchandise inspired by Gojo Satoru.', 1200, 'manga', 'volume', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 5.0, 512, 'gojo', true, 20),
('gojo-artbook-01', 'JJK Art Book — Gojo Chapter', 'gojo-artbook-01', 'JJK Art Book — Gojo Chapter - High-quality official merchandise inspired by Gojo Satoru.', 2800, 'manga', 'artbook', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.9, 89, 'gojo', false, 20),
('gojo-poster-01', 'Gojo Satoru Technique Art Print', 'gojo-poster-01', 'Gojo Satoru Technique Art Print - High-quality official merchandise inspired by Gojo Satoru.', 1800, 'wallart', 'poster', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.7, 42, 'gojo', false, 20),
('gojo-canvas-01', 'Gojo Satoru Canvas 50×70cm', 'gojo-canvas-01', 'Gojo Satoru Canvas 50×70cm - High-quality official merchandise inspired by Gojo Satoru.', 3500, 'wallart', 'canvas', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.8, 31, 'gojo', false, 20),
('gojo-figure-01', 'Gojo Satoru PVC Figure 25cm', 'gojo-figure-01', 'Gojo Satoru PVC Figure 25cm - High-quality official merchandise inspired by Gojo Satoru.', 6500, 'figurines', 'pvc', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg', '/images/gojo-card.jpg'], '{}', '{}', 4.9, 144, 'gojo', true, 20),
('gojo-nendo-01', 'Gojo Satoru Nendoroid', 'gojo-nendo-01', 'Gojo Satoru Nendoroid - High-quality official merchandise inspired by Gojo Satoru.', 8900, 'figurines', 'nendoroid', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 5.0, 201, 'gojo', false, 20),
('gojo-keychain-01', 'Gojo Satoru Keychain', 'gojo-keychain-01', 'Gojo Satoru Keychain - High-quality official merchandise inspired by Gojo Satoru.', 800, 'accessories', 'keychain', '/images/gojo-card.jpg', ARRAY['/images/gojo-card.jpg'], ARRAY['/images/gojo-card.jpg'], '{}', '{}', 4.4, 88, 'gojo', false, 20),

-- RYOMEN SUKUNA (11-20)
('sukuna-tshirt-01', 'Ryomen Sukuna Technique T-Shirt', 'sukuna-tshirt-01', 'Ryomen Sukuna Technique T-Shirt - High-quality official merchandise inspired by Ryomen Sukuna. Featured Artifact.', 2500, 'clothing', 't-shirt', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg', '/images/sukuna-card.jpg'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'White'], 4.8, 124, 'sukuna', true, 20),
('sukuna-hoodie-01', 'Ryomen Sukuna Signature Hoodie', 'sukuna-hoodie-01', 'Ryomen Sukuna Signature Hoodie - High-quality official merchandise inspired by Ryomen Sukuna.', 4800, 'clothing', 'hoodie', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Navy'], 4.9, 256, 'sukuna', false, 20),
('sukuna-pants-01', 'Ryomen Sukuna Training Pants', 'sukuna-pants-01', 'Ryomen Sukuna Training Pants - High-quality official merchandise inspired by Ryomen Sukuna.', 3200, 'clothing', 'pants', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 64, 'sukuna', false, 20),
('sukuna-manga-01', 'JJK Vol. 1 — Sukuna Edition', 'sukuna-manga-01', 'JJK Vol. 1 — Sukuna Edition - High-quality official merchandise inspired by Ryomen Sukuna.', 1200, 'manga', 'volume', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 5.0, 512, 'sukuna', true, 20),
('sukuna-artbook-01', 'JJK Art Book — Sukuna Chapter', 'sukuna-artbook-01', 'JJK Art Book — Sukuna Chapter - High-quality official merchandise inspired by Ryomen Sukuna.', 2800, 'manga', 'artbook', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.9, 89, 'sukuna', false, 20),
('sukuna-poster-01', 'Ryomen Sukuna Technique Art Print', 'sukuna-poster-01', 'Ryomen Sukuna Technique Art Print - High-quality official merchandise inspired by Ryomen Sukuna.', 1800, 'wallart', 'poster', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.7, 42, 'sukuna', false, 20),
('sukuna-canvas-01', 'Ryomen Sukuna Canvas 50×70cm', 'sukuna-canvas-01', 'Ryomen Sukuna Canvas 50×70cm - High-quality official merchandise inspired by Ryomen Sukuna.', 3500, 'wallart', 'canvas', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.8, 31, 'sukuna', false, 20),
('sukuna-figure-01', 'Ryomen Sukuna PVC Figure 25cm', 'sukuna-figure-01', 'Ryomen Sukuna PVC Figure 25cm - High-quality official merchandise inspired by Ryomen Sukuna.', 6500, 'figurines', 'pvc', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg', '/images/sukuna-card.jpg'], '{}', '{}', 4.9, 144, 'sukuna', true, 20),
('sukuna-nendo-01', 'Ryomen Sukuna Nendoroid', 'sukuna-nendo-01', 'Ryomen Sukuna Nendoroid - High-quality official merchandise inspired by Ryomen Sukuna.', 8900, 'figurines', 'nendoroid', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 5.0, 201, 'sukuna', false, 20),
('sukuna-keychain-01', 'Ryomen Sukuna Keychain', 'sukuna-keychain-01', 'Ryomen Sukuna Keychain - High-quality official merchandise inspired by Ryomen Sukuna.', 800, 'accessories', 'keychain', '/images/sukuna-card.jpg', ARRAY['/images/sukuna-card.jpg'], ARRAY['/images/sukuna-card.jpg'], '{}', '{}', 4.4, 88, 'sukuna', false, 20),

-- YUJI ITADORI (21-30)
('yuji-tshirt-01', 'Yuji Itadori Technique T-Shirt', 'yuji-tshirt-01', 'Yuji Itadori Technique T-Shirt - High-quality official merchandise inspired by Yuji Itadori. Featured Artifact.', 2500, 'clothing', 't-shirt', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg', '/images/yuji-card.jpg'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'White'], 4.8, 124, 'yuji', true, 20),
('yuji-hoodie-01', 'Yuji Itadori Signature Hoodie', 'yuji-hoodie-01', 'Yuji Itadori Signature Hoodie - High-quality official merchandise inspired by Yuji Itadori.', 4800, 'clothing', 'hoodie', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Navy'], 4.9, 256, 'yuji', false, 20),
('yuji-pants-01', 'Yuji Itadori Training Pants', 'yuji-pants-01', 'Yuji Itadori Training Pants - High-quality official merchandise inspired by Yuji Itadori.', 3200, 'clothing', 'pants', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 64, 'yuji', false, 20),
('yuji-manga-01', 'JJK Vol. 1 — Yuji Edition', 'yuji-manga-01', 'JJK Vol. 1 — Yuji Edition - High-quality official merchandise inspired by Yuji Itadori.', 1200, 'manga', 'volume', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 5.0, 512, 'yuji', true, 20),
('yuji-artbook-01', 'JJK Art Book — Yuji Chapter', 'yuji-artbook-01', 'JJK Art Book — Yuji Chapter - High-quality official merchandise inspired by Yuji Itadori.', 2800, 'manga', 'artbook', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.9, 89, 'yuji', false, 20),
('yuji-poster-01', 'Yuji Itadori Technique Art Print', 'yuji-poster-01', 'Yuji Itadori Technique Art Print - High-quality official merchandise inspired by Yuji Itadori.', 1800, 'wallart', 'poster', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.7, 42, 'yuji', false, 20),
('yuji-canvas-01', 'Yuji Itadori Canvas 50×70cm', 'yuji-canvas-01', 'Yuji Itadori Canvas 50×70cm - High-quality official merchandise inspired by Yuji Itadori.', 3500, 'wallart', 'canvas', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.8, 31, 'yuji', false, 20),
('yuji-figure-01', 'Yuji Itadori PVC Figure 25cm', 'yuji-figure-01', 'Yuji Itadori PVC Figure 25cm - High-quality official merchandise inspired by Yuji Itadori.', 6500, 'figurines', 'pvc', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg', '/images/yuji-card.jpg'], '{}', '{}', 4.9, 144, 'yuji', true, 20),
('yuji-nendo-01', 'Yuji Itadori Nendoroid', 'yuji-nendo-01', 'Yuji Itadori Nendoroid - High-quality official merchandise inspired by Yuji Itadori.', 8900, 'figurines', 'nendoroid', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 5.0, 201, 'yuji', false, 20),
('yuji-keychain-01', 'Yuji Itadori Keychain', 'yuji-keychain-01', 'Yuji Itadori Keychain - High-quality official merchandise inspired by Yuji Itadori.', 800, 'accessories', 'keychain', '/images/yuji-card.jpg', ARRAY['/images/yuji-card.jpg'], ARRAY['/images/yuji-card.jpg'], '{}', '{}', 4.4, 88, 'yuji', false, 20),

-- MEGUMI FUSHIGURO (31-40)
('megumi-tshirt-01', 'Megumi Fushiguro Technique T-Shirt', 'megumi-tshirt-01', 'Megumi Fushiguro Technique T-Shirt - High-quality official merchandise inspired by Megumi Fushiguro. Featured Artifact.', 2500, 'clothing', 't-shirt', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg', '/images/megumi-card.jpg'], ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'White'], 4.8, 124, 'megumi', true, 20),
('megumi-hoodie-01', 'Megumi Fushiguro Signature Hoodie', 'megumi-hoodie-01', 'Megumi Fushiguro Signature Hoodie - High-quality official merchandise inspired by Megumi Fushiguro.', 4800, 'clothing', 'hoodie', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Navy'], 4.9, 256, 'megumi', false, 20),
('megumi-pants-01', 'Megumi Fushiguro Training Pants', 'megumi-pants-01', 'Megumi Fushiguro Training Pants - High-quality official merchandise inspired by Megumi Fushiguro.', 3200, 'clothing', 'pants', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], ARRAY['M', 'L', 'XL'], ARRAY['Black'], 4.5, 64, 'megumi', false, 20),
('megumi-manga-01', 'JJK Vol. 1 — Megumi Edition', 'megumi-manga-01', 'JJK Vol. 1 — Megumi Edition - High-quality official merchandise inspired by Megumi Fushiguro.', 1200, 'manga', 'volume', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 5.0, 512, 'megumi', true, 20),
('megumi-artbook-01', 'JJK Art Book — Megumi Chapter', 'megumi-artbook-01', 'JJK Art Book — Megumi Chapter - High-quality official merchandise inspired by Megumi Fushiguro.', 2800, 'manga', 'artbook', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.9, 89, 'megumi', false, 20),
('megumi-poster-01', 'Megumi Fushiguro Technique Art Print', 'megumi-poster-01', 'Megumi Fushiguro Technique Art Print - High-quality official merchandise inspired by Megumi Fushiguro.', 1800, 'wallart', 'poster', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.7, 42, 'megumi', false, 20),
('megumi-canvas-01', 'Megumi Fushiguro Canvas 50×70cm', 'megumi-canvas-01', 'Megumi Fushiguro Canvas 50×70cm - High-quality official merchandise inspired by Megumi Fushiguro.', 3500, 'wallart', 'canvas', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.8, 31, 'megumi', false, 20),
('megumi-figure-01', 'Megumi Fushiguro PVC Figure 25cm', 'megumi-figure-01', 'Megumi Fushiguro PVC Figure 25cm - High-quality official merchandise inspired by Megumi Fushiguro.', 6500, 'figurines', 'pvc', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg', '/images/megumi-card.jpg'], '{}', '{}', 4.9, 144, 'megumi', true, 20),
('megumi-nendo-01', 'Megumi Fushiguro Nendoroid', 'megumi-nendo-01', 'Megumi Fushiguro Nendoroid - High-quality official merchandise inspired by Megumi Fushiguro.', 8900, 'figurines', 'nendoroid', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 5.0, 201, 'megumi', false, 20),
('megumi-keychain-01', 'Megumi Fushiguro Keychain', 'megumi-keychain-01', 'Megumi Fushiguro Keychain - High-quality official merchandise inspired by Megumi Fushiguro.', 800, 'accessories', 'keychain', '/images/megumi-card.jpg', ARRAY['/images/megumi-card.jpg'], ARRAY['/images/megumi-card.jpg'], '{}', '{}', 4.4, 88, 'megumi', false, 20);
